### PR TITLE
Update version of multiapps plugin to 2.1.3

### PR DESCRIPTION
**Pull request by boyan-velinov**

### CODE REVIEW

**Comment by abbyachau** [comment]
Thanks, @boyan-velinov!

**Comment by abbyachau** [comment]
Hi @boyan-velinov we are creating a new [v7 plugin interface](https://github.com/cloudfoundry/cli/tree/master/plugin/v7) and are developing new methods which call the v3 API. We noticed that you use the [AccessToken](https://github.com/cloudfoundry/cli/blob/master/plugin/plugin.go#L37) method and wonder what your use case is? If we didn't support it on v7, what would you use instead? Thanks!

**Comment by boyan-velinov** [comment]
Hi @abbyachau 

Thanks for notifying us!

We use AccessToken from our MTA CF CLI plugin, as you noticed. Then it is passed to [Multiapps Controller ](https://github.com/cloudfoundry-incubator/multiapps-controller) backend. Multiapps Controller contains all of the business logic and operates on behalf of the user with that token. All consequent calls from Multiapps Controller to Cloud Controller are done with that token, e.g creating services, creating apps and so on.

**Comment by abbyachau** [comment]
Thank you @boyan-velinov  appreciate the feedback. We'll reach out if we have any follow-up questions, thanks again!

**Pull request merged**
