### PR TITLE
Replace Old mysql-plugin

### PR DESCRIPTION
**Pull request by elliott-neal**
This PR will extend the outdated and unmaintained mysql-plugin to support rdsmysql.

### CODE REVIEW

**Comment by elliott-neal** [comment]
Hello, what all do I need to do to sign the CLA?

**Comment by a-b** [comment]
Hi @elliott-neal if your organization is not listed you can proceed as an individual contributor.

**Comment by a-b** [comment]
Hello @elliott-neal ! Can you please update EasyCLA?
We are curious why you choose to change plugin repository over making PR to the original?

**Comment by jdgonzaleza** [comment]
Hi @elliott-neal It's been quite sometime since there was un update to this PR. We'll be closing it for now. If you feel like this is very important, please reopen it.

**Pull request closed without merging**
