### PR TITLE
Added DefaultEnv

### PR DESCRIPTION
**Pull request by andrewlunde**
## Description of the Change

Adding DefaultEnv plugin for a teammate(Philip Mugglestone).

  description: Create default-env.json file with environment variables of an app.
  homepage: https://github.com/saphanaacademy/DefaultEnv

-Andrew

### CODE REVIEW

**Comment by a-b** [comment]
Hi @andrewlunde ! Thanks for contributing a new plugin. Can you please share your release pipeline via Github Actions? We want to make sure that the source code and binaries from the release are matching.

**Comment by andrewlunde** [comment]
_share your release pipeline via Github Actions?_

I don't have this under CI/CD so I don't have a pipeline to share.

I could coordinate a code commit and release so that there isn't a large disparity in the dates.  Would that be sufficient?

-Andrew

**Comment by andrewlunde** [comment]
I'm unclear what action I need to take to move this request forward.  Hints?

-Andrew

**Comment by a-b** [comment]
Sorry for the late response, I believe we should be ok to move forward. The reason I asked about the build a pipeline is to protect plugin users from unexpected behavior of binaries in the manifest.

The best practice is to setup a GitHub Actions pipeline that will build and make releases in the public cloud, so it is verifyable.

**Pull request merged**
