### PR TITLE
Move to Go modules

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by abbyachau** [comment]
Hi @drnic thanks for this pull request. The CF CLI engineering team plan on discussing this change and will get back to you as soon as they can. Thanks again.

**Comment by abbyachau** [comment]
cc @acrmp

**Comment by ericpromislow** [comment]
LGTM

Eric and @JenGoldstrich

**Comment by ericpromislow** [comment]
We had to back out this PR as it failed on our CI

You can repo the problem locally by running `cf push plugins` in the main dir (after editing manifest.yml to use routes you have access to)

**Pull request merged**
