### PR TITLE
Update ApplicationDataBackupRestore cli plugin version to 0.4.0

### PR DESCRIPTION
**Pull request by ryanwittrup**
Thank you for contributing to the CF CLI Plugin Repository!

This repo contains both the plugin repo server and the metadata for CLI
community plugins.
Some of the requirements for PRs will apply to only one of these parts.

We're not allowed to accept any PRs without a signed CLA, no matter how small.
If your contribution falls under a company CLA but your membership is not public, expect delays while we confirm.

# Submitting Plugins

If you haven't yet, please review our contributing guidelines:  
https://github.com/cloudfoundry/cli-plugin-repo#submitting-plugins

In particular ensure the following requirements are being met:
* [X] The plugin's `name` field in `repo-index.yml` matches the `Name` field in the plugin's `plugin.PluginMetadata` section
* [X] The plugin's `url` field in `repo-index.yml` contains the same version from the `version` field

# Submitting PRs to CLIPR (the CLI Plugin Repo server)

All new code requires tests to protect against regressions.

## Description of the Change

Update help text to accurately reflect command

Previously help was showing `cf adbr status` but the "real" command is `cf adbr get-status`

## Why Is This PR Valuable?

To help reduce user confusion - this bug came up based on a support engineer providing feedback from working with a customer

## Applicable Issues

NA

## How Urgent Is The Change?

Not especially urgent - current risk is low, and the functionality works fine, so this is just about being more clear / accurate in the documentation from `cf help`

## Other Relevant Parties

NA

### CODE REVIEW

**Comment by kimago** [comment]
Please ignore this PR: We (= mysql team) will soon replace it with one hopefully free of issues. We are leaving this here for reference for the time being, but expect to delete it by EOD 5/10/22.

**Comment by kimago** [comment]
The **EasyCLA** check still fails, despite me identifying myself as a VMware employee, which EasyCLA seemed to immediately accept without further input required. Yet the above check is still failing.

Q: Would securing a "VMware" Organization on my github profile make EasyCLA pass its check?

Context:
- I am VMware by way of Pivotal, updating one of our CF mysql backup plugins.
- I've always used my personal github profile `kimago` not a company one, which may be the source of the problem here.
- My profile shows I'm a member of the "Cloud Foundry" organization, but selecting "Cloudfoundry" from EasyCLI's organization menus led me to a form requesting the contact info for my CLA Administrator, which I don't know. (And VMware is the more correct answer here, I'm not actively employed by cloudfoundry.org / CNCF.)

**Comment by kimago** [comment]
UPDATE: PR checks passed, please accept/merge when you can.  Disregard our earlier (since removed) "ignore this PR" comment; PR is valid and should be merged.

**Comment by colins** [comment]
Morning @a-b or @jdgonzaleza could you review and merge this, please?

**Review by jdgonzaleza — APPROVED** [review]
LGTM

**Comment by kimago** [comment]
@jdgonzaleza Thanks for merging this.

Question: Do you know when might we see this ApplicationDataBackupRestore 0.4.0 plugin uploaded to the [Cloudfoundry Plugin page](https://plugins.cloudfoundry.org/#ApplicationDataBackupRestore)? If you aren't sure, who might be able to answer that for us?

Thanks again.

**Comment by jdgonzaleza** [comment]
Hi @kimago.
We are currently experiencing some issues with the deployment of the updated plugins page. Our team is currently working on this and will let you know when the page is properly updated and deployed. 
Sorry for the inconvenience.

**Comment by jdgonzaleza** [comment]
@kimago Plugins page already updated! It seems like ApplicationDataBackupRestore 0.4.0 it's now visible.

**Pull request merged**
