### PR TITLE
Updating service-use to 1.2.1

### PR DESCRIPTION
**Pull request by cdelashmutt-pivotal**

### CODE REVIEW

**Comment by cdelashmutt-pivotal** [comment]
Ok, made the plugin name consistent, and rev'd to 1.2.2.

**Comment by vitreuz** [comment]
@cdelashmutt-pivotal the plugin version is mismatched. The repo is listing it as 1.2.1 but the plugin is showing 1.2.2.

**Comment by cdelashmutt-pivotal** [comment]
Sorry about that.  Hopefully I didn't forget anything else!

**Comment by cdelashmutt-pivotal** [comment]
Hmm.  That failure doesn't seem to be under my control.

**Pull request merged**
