### PR TITLE
Submitting ServiceManagement plugin

### PR DESCRIPTION
**Pull request by andrewlunde**
#Submitting Plugins

I have reviewed our contributing guidelines:  
https://github.com/cloudfoundry/cli-plugin-repo#submitting-plugins

These requirements are being met:
* [x] The plugin's `name` field in `repo-index.yml` matches the `Name` field in the plugin's `plugin.PluginMetadata` section
* [x] The plugin's `url` field in `repo-index.yml` contains the same version from the `version` field

Please consider my submission and let me know if I need to provide any additions and/or corrections.

-Andrew
andrew.lunde@sap.com

### CODE REVIEW

**Comment by heyjcollins** [comment]
Hi @andrewlunde - thanks for submitting this plugin update.
Please complete the CLA authorization process and we'll be happy to accept your PR.
- [**Please click here to be authorized**](https://api.lfcla.com/v2/repository-provider/github/sign/1797134/29622333/365). 
For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

**Comment by andrewlunde** [comment]
I believe I now have the required CLA.  When going to the EasyCLA screen I just get a blank screen where before I was prompted to pick my company(SAP).

Can we proceed?

-Andrew

**Comment by andrewlunde** [comment]
Have now gotten the CLA straightened out.
-Andrew

**Comment by andrewlunde** [comment]
Seems I'm legit now.  When's the PR merge?
-Andrew

**Comment by andrewlunde** [comment]
I've gotten an official SAP repo created to host the plugin code/binaries.
Have updated repo-index.yml with the details/checksums.

Let me know if you need further details.
-Andrew

**Comment by heyjcollins** [comment]
Thanks @andrewlunde - CLA is all clear but now it's failing the travis-ci build. Please have a look and if you need any assistance, feel free to ping us in the #cli channel of CloudFoundry Slack.

**Comment by andrewlunde** [comment]
Had changed name in yaml but not in my project to match.  Fixed and building now.
-Andrew

**Comment by andrewlunde** [comment]
Fixed and building now.

-Andrew
+1 404-416-5688 Cell

**Pull request merged**
