### PR TITLE
Increase version of multiapps to 2.2.0

### PR DESCRIPTION
**Pull request by enchobelezirev**

### CODE REVIEW

**Comment by abbyachau** [comment]
Hi @enchobelezirev thanks for this. It looks like there's a CI failure, please review when you get the chance and we can merge this in as soon as it goes green. Thanks.

**Comment by abbyachau** [comment]
hey @enchobelezirev a ping on this - please look into the failures and we can merge this in when Travis is green. Thanks.

**Comment by enchobelezirev** [comment]
Hello, I have forgotten about this - sorry for that. Will look into it and will proceed with some fix.

Thanks!

**Comment by enchobelezirev** [comment]
Hello @abbyachau,

The tests have passed. Could you check it - thanks!

**Comment by abbyachau** [comment]
Thank you @enchobelezirev, merged.

**Pull request merged**
