### PR TITLE
Add HTML5 Plugin v1.1.0

### PR DESCRIPTION
**Pull request by micellius**

### CODE REVIEW

**Comment by micellius** [comment]
> ❌ Hey micellius!
> 
> All pull request submitters and commit authors must have a Contributor License Agreement (CLA). Click [here](https://www.cloudfoundry.org/cla) for details on the CLA process.
> 
> The following github user @micellius is not covered by a CLA.
> 
> After the CLA process is complete, this pull request will need to be closed & reopened. DreddBot will then validate the CLA(s).

I'm [publicized member](https://github.com/orgs/SAP/people?utf8=%E2%9C%93&query=micellius)  of https://github.com/SAP organization. SAP has a Corporate CLA

**Comment by abbyachau** [comment]
Hi @micellius thanks for this, once you've signed the CLA we can pull this in. Thanks.

**Comment by micellius** [comment]
Hi @abbyachau ,
I have both corporate and individual CLA signed and sent to contributers@cloudfoundry.org. I closed and reopened the PR, but DreddBot still does not recognize my CLAs. Can you please merge my PR.

**Comment by christopherclark** [comment]
@abbyachau  - confirming here that @micellius has signed the CLA.  Not sure what's happening with Dredddbot (it does take a little while for changes to be reflected - but usually not this long).  I'll reach out to the toolsmiths team if this problem persists.  In the meantime, you can proceed with this PR.  Thanks!

**Comment by willmurphyscode** [comment]
@micellius Sorry for all the DreddBot noise.

**Pull request merged**
