### PR TITLE
Update Swisscom Application Cloud plugin to v0.2.0

### PR DESCRIPTION
**Pull request by cloudmarius**
# Submitting Plugins

If you haven't yet, please review our contributing guidelines:  
https://github.com/cloudfoundry/cli-plugin-repo#submitting-plugins

In particular ensure the following requirements are being met:
* [x] The plugin's `name` field in `repo-index.yml` matches the `Name` field in the plugin's `plugin.PluginMetadata` section
* [x] The plugin's `url` field in `repo-index.yml` contains the same version from the `version` field

# Submitting PRs to CLIPR (the CLI Plugin Repo server)

All new code requires tests to protect against regressions.

## Description of the Change

We allow our users to create a Let's Encrypt certificate with RSA or ECDSA keys.

## Why Is This PR Valuable?

Users will benefit from using smaller, faster and more secure ECDSA certificates.
Without this new release, they have to always use RSA.

## Applicable Issues

N.A.

## How Urgent Is The Change?

It's not very urgent.

## Other Relevant Parties

Nobody else is affected.

### CODE REVIEW

**Comment by cloudmarius** [comment]
Hi @a-b, @jdgonzaleza, can you please have a look at this Pull Request?

As far as I know, Swisscom is covered by a valid CLA for all Cloudfoundry contributions. Could you please guide me in clarifying if this is still true?

Thank you!

**Comment by jdgonzaleza** [comment]
Hi @cloudmarius I assume you already requested the authorization, right? if that's not the case I would do that through [here](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/1797134/29622333/406/#/?version=2) and then follow with Corporate Contribution path and search for Swisscom. 
If you already did that and still not working, I recommend you contact the people on Swisscom in charge of giving this authorization.

**Comment by cloudmarius** [comment]
Thank you for your help so far @jdgonzaleza.

As far as I know, other Swisscom employees made similar contributions over the years and they were benefiting from being public members of https://github.com/swisscom.
I'm following the 'Corporate Contributor' flow and I'm expected to provide a CLA Manager - and I have no idea where to get it from - is this configured on the LF side? Any hint is greatly appreciated :smile:

**Comment by jdgonzaleza** [comment]
@cloudmarius I don't know who are the cla managers for Swisscom 😕 or how that's being configured. I suggest you to ask in the [cloudfoundry slack's general channel](https://cloudfoundry.slack.com/archives/C02FL4A2K), there must be someone who can point you in to the right direction.

**Comment by cloudmarius** [comment]
EasyCLA is now happy. Ready for review and merge @jdgonzaleza.

**Pull request merged**
