### PR TITLE
Make plugin names anchors so that individual plugins can be linked to

### PR DESCRIPTION
**Pull request by aeijdenberg**
Show para icon when hovering over header, in the same manner as
godoc.org does.

### CODE REVIEW

**Comment by Ema93sh** [comment]
Hi @aeijdenberg. Thanks for creating this pull request. This is a useful feature to have. We found the link difficult to click and would love if you could either make the `span` bigger so that icon does not disappear or make the entire header (name with the version) as a link.

**Comment by aeijdenberg** [comment]
@Ema93sh - changed as suggested. Not sure why the build insta-failed - I don't think it's related to the content of this PR.

**Comment by willmurphyscode** [comment]
This looks great! Thank you very much for the good idea and the implementation!

**Comment by willmurphyscode** [comment]
Hi @aeijdenberg,

Thanks again for the contribution, and sorry to bother about something we thought was done, but it seems like angular does not play nicely with this sort of anchor tag.

For example, if you go to: https://plugins.cloudfoundry.org/#log-noise you will notice that we don't scroll down on the first page load, but after the page is loaded, then the link will start to work.

We started looking into this ourselves, but don't have the cycles to look into it further. If you have the time and inclination, we would welcome another PR.

Thanks!

**Pull request merged**
