### PR TITLE
Update top plugin to v0.9.4

### PR DESCRIPTION
**Pull request by kkellner**

### CODE REVIEW

**Comment by kkellner-cl** [comment]
The challenges I have in using the V3 API is the inability to access the needed information in an efficient manner.   E.g.   To get isolation segment information for all org/spaces I can call two APIs `/v2/apps` and `/v2/organization`.   These APIs return iso seg info.   However with v3 api I need to call `/v3/isolation_segments/:guid/relationships/organizations` and `/v3/isolation_segments/:guid/relationships/spaces` for every iso seg -- which is far more calls then is reasonable to support this plugins functionality.    There are other examples of this as well, iso seg is just one example.

**Comment by selzoc** [comment]
hi @kkellner ,
On the V3 api, we've been handling cases like this with `include` query parameters.  You can see an example on the list apps endpoint: http://v3-apidocs.cloudfoundry.org/version/3.74.0/index.html#list-apps

Would a `include` parameter for `orgs` and `spaces` on the `/v3/isolation_segments` satisfy your use case?

**Comment by kkellner** [comment]
First, I think I need to understand how the "include" works.   I've tried this:

```
cf curl "/v3/spaces?include=org"
{
   "errors": [
      {
         "detail": "The query parameter is invalid: Unknown query parameter(s): 'include'",
         "title": "CF-BadQueryParameter",
         "code": 10005
      }
   ]
}
```
API info:
```
      "cloud_controller_v3": {
         "href": "https://api.system.example.io/v3",
         "meta": {
            "version": "3.70.0"
         }
      },
```

Am I doing something wrong?

As for the isolation segment relationship inclusion (assuming I can figure out how it works), would be perfect if I can get this info from orgs (for the default assigned isolation segment) via `/v3/organizations` and for space (for the currently assigned iso segment if not default) via `/v3/spaces`

The next thing I ran into when looking at updating to V3 API is getting "staging" info -- really I just want to know if a newly pushed app is still in staging.  The was available in the `/v2/apps` output as a field:
```
"package_state": "STAGED", 
```
This would show `PENDING` if staging has not completed.   I use this info to give visual feedback if a droplet has not yet been created.   I know V3 has moved staging info into `/v3/droplets`.  Would it be crazy to have an `include` in /v3/apps` to include droplet info?   Maybe that would be too much info and/or to expensive of call to make.

**Comment by ssisil** [comment]
@kkellner - This feature became available in `3.71.0`.  We would simply include the associated iso segments in the `included` section of Org and Space

**Comment by kkellner** [comment]
What are your thoughts about "droplets" included in /v3/apps?  Is that too much info to include?

**Comment by ssisil** [comment]
I think its something we can evaluate. Its an established pattern in our API - so it boils down to if the `include` would impact performance.  We can discuss as team - but stay tuned.

**Comment by abbyachau** [comment]
Hi @kkellner we are creating a new [v7 plugin interface](https://github.com/cloudfoundry/cli/tree/master/plugin/v7) and are developing new methods which call the v3 API. We noticed that you use the [AccessToken](https://github.com/cloudfoundry/cli/blob/master/plugin/plugin.go#L37) method and wonder what your use case is? If we didn't support it on v7, what would you use instead? Thanks!

**Comment by kkellner** [comment]
@abbyachau 

There are two uses of AccessToken in this plugin:

1. It's a required param to FirehoseWithoutReconnect.  Example: dopplerConnection.FirehoseWithoutReconnect(subscriptionID, authToken).
https://github.com/ECSTeam/cloudfoundry-top-plugin/blob/aacf874506e8db31eeb7612b57d506e9e47a86d3/top/client.go#L269

2. Because the top plugin can run for many days, the token can expire.  When this happens, I call NewTokenRefresher which contains cliConnection.AccessToken() to refresh the token.
https://github.com/ECSTeam/cloudfoundry-top-plugin/blob/a4b69912b5d37ec9cad4da72062859b18768de02/top/tokenRefresher.go#L37

I am not familiar with the new API -- if the firehose API no longer needs a token param and if there is no token refreshing needed, then is sounds like it can be removed.  But these are big "ifs".

**Comment by abbyachau** [comment]
Thank you @kkellner appreciate the feedback. We'll reach out if we have any follow-up questions, thanks again!

**Pull request merged**
