### PR TITLE
Update DefaultEnv to 1.1.0

### PR DESCRIPTION
**Pull request by darmiel**
The [saphanaacademy/defaultenv](https://github.com/saphanaacademy/defaultenv) repository is no longer active, as the SAP Hana Academy was closed at the end of last year. Tom and I have taken over the development and the repository now lives in the `sap`-organization.

# Submitting Plugins

* [x] The plugin's `name` field in `repo-index.yml` matches the `Name` field in the plugin's `plugin.PluginMetadata` section
* [x] The plugin's `url` field in `repo-index.yml` contains the same version from the `version` field

### CODE REVIEW

**Comment by moleske** [comment]
Thanks for the update @darmiel! Once you've signed the CLA we can merge this

**Comment by moleske** [comment]
I see in the [1.1.0 release that there's an arm osx release](https://github.com/SAP/cf-cli-defaultenv-plugin/releases/tag/v1.1.0), but that it is not listed in this pr.  If you want to add it here's an [example with amd and arm osx releases](https://github.com/cloudfoundry/cli-plugin-repo/blob/main/repo-index.yml#L1686-L1691).  Or let me know if you don't want to list the osx arm release here.

**Comment by darmiel** [comment]
I wasn't sure how the CLI distinguishes which of the two is the amd64 and arm64 release. 
Does it take the type from the filename, or do I simply add both releases under `platform: osx` and it downloads both and checks which fits for arm64 / amd64?

I had only found the following code snippet, which didn't help me either: 
https://github.com/cloudfoundry/cli/blob/main/cf/actors/plugininstaller/plugin_downloader.go#L39

**Comment by moleske** [comment]
Hmmm good question.  I'll have to try and find a mac to test this out with the existing plugins that define two osx files.  Maybe one of the @cloudfoundry/wg-app-runtime-interfaces-cli-approvers ?

**Comment by darmiel** [comment]
I've tried it out with an Intel Mac and a M1 Mac. **Both** download the following binary when running `cf install-plugin spring-cloud-services`:

```http
GET https://github.com/pivotal-cf/spring-cloud-services-cli-plugin/releases/download/v1.0.25/spring-cloud-services-cli-plugin-darwin-amd64-1.0.25
```

**Comment by moleske** [comment]
I'll go ahead and merge this as is.  I've asked in the [cli channel on slack ](https://cloudfoundry.slack.com/archives/C032824SM/p1712884968302029)to see if others know

**Review by moleske — APPROVED** [review]

**Pull request merged**
