### PR TITLE
add new autopilot cli-plugin application

### PR DESCRIPTION
**Pull request by HappyTobi**
Add new autopilot cli-plugin
Plugin will be active maintained

### CODE REVIEW

**Comment by jenspinney** [comment]
Hey @HappyTobi. Thanks for fixing up the failures reported by Travis. Once you sign the CLA (or publicize your membership in an organization that's has a org-wide CLA), just close and re-open the pull request to get cfdreddbot to trigger again, and we'll merge this. The comment from cfdreddbot above has a link for more info on how to sign the CLA or publicize org membership.

**Comment by HappyTobi** [comment]
> Hey @HappyTobi. Thanks for fixing up the failures reported by Travis. Once you sign the CLA (or publicize your membership in an organization that's has a org-wide CLA), just close and re-open the pull request to get cfdreddbot to trigger again, and we'll merge this. The comment from cfdreddbot above has a link for more info on how to sign the CLA or publicize org membership.

Thanks I've done that

**Comment by jenspinney** [comment]
Great, thanks!

**Comment by jenspinney** [comment]
Hi @HappyTobi,

We realized after merging this that there are now two `autopilot` commands. I tried to rename yours to `tobi-autopilot` in the YAML file to avoid confusion, but then we hit an error because your plugin binary's name needs to match the name in the YAML file.

To get around this, I reverted this merge, but we welcome you to resubmit it with a different name from the existing `autopilot`. Sorry for the inconvenience!

**Comment by HappyTobi** [comment]
@jenspinney no Problem will change that and update the pull request.

Kind regards

**Pull request merged**
