### PR TITLE
Update html5-plugin to 1.4.6

### PR DESCRIPTION
**Pull request by micellius**
Thank you for contributing to the CF CLI Plugin Repository!

This repo contains both the plugin repo server and the metadata for CLI
community plugins.
Some of the requirements for PRs will apply to only one of these parts.

We're not allowed to accept any PRs without a signed CLA, no matter how small.
If your contribution falls under a company CLA but your membership is not public, expect delays while we confirm.

# Submitting Plugins

If you haven't yet, please review our contributing guidelines:  
https://github.com/cloudfoundry/cli-plugin-repo#submitting-plugins

In particular ensure the following requirements are being met:
* [x] The plugin's `name` field in `repo-index.yml` matches the `Name` field in the plugin's `plugin.PluginMetadata` section
* [x] The plugin's `url` field in `repo-index.yml` contains the same version from the `version` field

# Submitting PRs to CLIPR (the CLI Plugin Repo server)

All new code requires tests to protect against regressions.

## Description of the Change

This is a minor update that allows to leverage additional configuration option in multiple commands provided by the plugin (with `-di` option), which brings convenience to the end-users and automates the setup required to consume HTML5 applications on SAP Business Technology Platform (former SAP Cloud Platform). The change also addresses some bug fixes and simplifies the process of HTML5 applications discovery when custom runtime is used to serve HTML5 applications (with `-rt` option).

## Why Is This PR Valuable?

With this PR users would gain convenient way of installing/updating the latest version of CF CLI plugin.

## Applicable Issues

- https://github.com/SAP/cf-html5-apps-repo-cli-plugin/issues/42
- https://github.com/SAP/cf-html5-apps-repo-cli-plugin/issues/43
- https://github.com/SAP/cf-html5-apps-repo-cli-plugin/issues/44
- https://github.com/SAP/cf-html5-apps-repo-cli-plugin/issues/45

## How Urgent Is The Change?

The change is not time-sensitive and may be handled with medium priority.

## Other Relevant Parties

The change is backward-compatible and other parties should not be affected.

### CODE REVIEW

**Comment by micellius** [comment]
I have a signed CLA, and my previous PRs were accepted (e.g. #367, #348, #311, #288 and #280), but the EasyCLA is red...

**Comment by IObert** [comment]
@a-b I noticed that the latest plugin version is still missing here <https://plugins.cloudfoundry.org/>

Actually, the result of the last PR (#375) is also still missing here. Is there something broken in the CI/CD pipeline?

**Comment by a-b** [comment]
Thanks for reporting!

We will take a look and get back to you shortly. I suspect this has something to do with broken CD related to the recent migration of our infrastructure.

**Comment by IObert** [comment]
@a-b I'm sorry to bother you. Do you have any news on this?

**Pull request merged**
