### PR TITLE
Update Event Alerts Plugin version to 0.0.1

### PR DESCRIPTION
**Pull request by pcf-event-alerts-cibot**

### CODE REVIEW

**Comment by wfernandes** [comment]
@dkoper Thanks for the feedback we created this new PR that addresses the concerns you had. 
- We updated the description to mention the plugin is meant for PCF
- We updated the homepage of the plugin to point to our docs site which includes information about the CLI plugin repo.

**Comment by XenoPhex** [comment]
@wfernandes it appears that in other pull requests people are swapping out spaces for dashes in the plugin name.

Is this something you'd like to do before I merge this pull request?

**Comment by wfernandes** [comment]
@XenoPhex We just discussed and decided to not replace the spaces with dashes.
Thanks for checking with us though.
We hope to update the name anyways once we upgrade it from beta.

**Comment by jbpivotal** [comment]
@wfernandes FYI, it looks like the plugin repo name to install the plugin (install from plugin repo flow) is different from the plugin binary name to uninstall it. You may want to revise so they're the same. Otherwise, I was able to install and uninstall it.

**Comment by wfernandes** [comment]
@jbpivotal Thanks for the feedback. I've added a in our backlog to track this.

**Pull request merged**
