### PR TITLE
Added V1.0.0 of CreateServicePush Plugin to repo-index.yml

### PR DESCRIPTION
**Pull request by dawu415**
Updated the repo-index.yml to submit for publication of the Create Service Push plugin.

### CODE REVIEW

**Comment by dkoper** [comment]
@dawu415 If you are covered by a CLA, please make the corresponding org (`pivotal-cf`?) public on your GitHub profile so that our bot can give us the OK.

**Comment by dawu415** [comment]
Thanks Dies. I’ve already made pivotal-services public, which I had checked should cover the CLA.  

Do I need to submit something on the PR to reissue another check?

**Comment by dkoper** [comment]
@chipchilders Can you confirm whether @dawu415 is covered by the CLA?
His membership of the `pivotal-services` is public, which he believes should be covered, but the bot doesn't seem to agree.

**Comment by chipchilders** [comment]
Should be one of:
  - pivotal
  - pivotal-cf
  - Pivotal-Field-Engineering
  - pivotal-golang

**Comment by dawu415** [comment]
Thanks! I've updated to pivotal-cf

**Pull request merged**
