### PR TITLE
Update Java Plugin to 3.0.1

### PR DESCRIPTION
**Pull request by TimGerlach**
Thank you for contributing to the CF CLI Plugin Repository!

This repo contains both the plugin repo server and the metadata for CLI
community plugins.
Some of the requirements for PRs will apply to only one of these parts.

We're not allowed to accept any PRs without a signed CLA, no matter how small.
If your contribution falls under a company CLA but your membership is not public, expect delays while we confirm.

# Submitting Plugins

If you haven't yet, please review our contributing guidelines:  
https://github.com/cloudfoundry/cli-plugin-repo#submitting-plugins

In particular ensure the following requirements are being met:
* [X] The plugin's `name` field in `repo-index.yml` matches the `Name` field in the plugin's `plugin.PluginMetadata` section
* [X] The plugin's `url` field in `repo-index.yml` contains the same version from the `version` field

# Submitting PRs to CLIPR (the CLI Plugin Repo server)

All new code requires tests to protect against regressions.

## Description of the Change

We must be able to understand the design of your change from this description.
Keep in mind that the maintainer reviewing this PR may not be familiar with or
have worked with the code here recently, so please walk us through the concepts.

## Why Is This PR Valuable?

What benefits will be realized by the code change? What users would want this change? What user need is this change addressing?

## Applicable Issues

List any applicable Github Issues here

## How Urgent Is The Change?

Is the change urgent? If so, explain why it is time-sensitive.

## Other Relevant Parties

Who else is affected by the change?

### CODE REVIEW

**Comment by TimGerlach** [comment]
Hi @a-b, @jdgonzaleza, can you please have a look at this Pull Request?

**Comment by TimGerlach** [comment]
Thanks a lot, @jdgonzaleza!
Can you also merge the PR, as I don't seem to have privileges to merge it by myself.

**Comment by TimGerlach** [comment]
Great, thank you very much 👍

**Comment by TimGerlach** [comment]
Hi @jdgonzaleza,
although the PR has been merged, I don't see the update in the Plugin catalog at https://plugins.cloudfoundry.org.
Am I missing something?

**Comment by jdgonzaleza** [comment]
Hi @TimGerlach,
thanks for reaching out. It seems like repo-index.yml was not properly sorted and that was why the Plugins catalog was not updated. 
Could you please review  [the catalog](https://plugins.cloudfoundry.org.)?  I sorted repo-index.yml

**Comment by TimGerlach** [comment]
It works now! Thanks a lot, @jdgonzaleza.

**Pull request merged**
